import type { Concept, Edge, Recipe, Source } from './types.js';

export const categories = [
  { id: 'nature', title: '自然与资源', en: 'NATURE / RESOURCES' },
  { id: 'making', title: '生产与协作', en: 'MAKING / PEOPLE' },
  { id: 'infrastructure', title: '基础设施', en: 'INFRASTRUCTURE' },
  { id: 'exchange', title: '交换与判断', en: 'EXCHANGE / EVIDENCE' },
];
export const sources: Source[] = [
  { id: 'fao-chain', title: 'Sustainable Food Value Chains: What is it?', publisher: 'FAO · 联合国粮农组织', url: 'https://www.fao.org/sustainable-food-value-chains/what-is-it/en/', scope: '食物价值链的生产、聚合、加工、分销及参与者关系；不是某块面包的实际溯源记录。', checked: '2026-09-14' },
  { id: 'food-dollar', title: 'Food Dollar — the domestic food supply chain', publisher: 'USDA · 美国农业部经济研究局', url: 'https://www.ers.usda.gov/data-products/food-dollar', scope: '美国食品支出的核算框架。这里仅用于解释成本环节，不把美国平均值套到你的面包。', checked: '2026-09-14' },
  { id: 'food-loss', title: 'SDG 12.3.1 · Global food losses', publisher: 'FAO · 联合国粮农组织', url: 'https://www.fao.org/sustainable-development-goals-data-portal/data/indicators/1231-global-food-losses/en/', scope: '收获后、运输、储存、批发与加工环节的食物损失；不用于判断具体食品能否食用。', checked: '2026-09-14' },
  { id: 'electricity', title: 'Electricity explained', publisher: 'EIA · 美国能源信息署', url: 'https://www.eia.gov/energyexplained/electricity/', scope: '电能转换、能源载体与用途。不涉及电气操作指导。', checked: '2026-09-14' },
  { id: 'water', title: 'Irrigation management', publisher: 'FAO · 联合国粮农组织', url: 'https://www.fao.org/land-water/water/agricultural-water-management/irrigation/en', scope: '农业用水、灌溉与管理；本页未采用动态统计数值。', checked: '2026-09-14' },
  { id: 'packaging', title: 'Packaging · from shelf to kitchen table', publisher: 'European Commission · 欧盟委员会', url: 'https://food.ec.europa.eu/food-safety/campaign-2026/packaging_en', scope: '包装保护食品的一般功能。文中欧盟法规不应自动应用于其他地区。', checked: '2026-09-14' },
  { id: 'science', title: 'Understanding Science: how science works', publisher: 'UC Berkeley · 加州大学伯克利分校', url: 'https://newsarchive.berkeley.edu/news/media/releases/2009/01/08_understandingscience.shtml', scope: '科学探索是动态过程，而非僵硬的单向步骤。本站观察练习是自编教学设计。', checked: '2026-09-14' },
];

const common = { jurisdiction: '一般机制 · 具体供应链依地区而异', lastReviewed: '2026-09-14' };
export const concepts: Concept[] = [
  { ...common, id:'energy', title:'能源', en:'ENERGY', category:'nature', index:'01', x:155, y:120, icon:'energy',
    summary:'你看不见的动力，也藏在每一块面包里。',
    why:'种植、加工、移动和保存，都需要让某种变化发生。能源把这些环节连接起来。',
    fact:'电是一种能源载体，可以由其他能源转换而来，再用于驱动机械或产生热。',
    mechanism:'沿着“能源 → 设备 → 变化”看：电机让机器转动，烤炉提供热。这里把多种能源合并成一个节点，便于观察跨系统依赖。',
    inputs:['一次能源','转换设备'], process:'转换与传递', outputs:['机械运动','热','电力'],
    recommendedBefore:[], failure:'供应中断可能限制设备运转；能效不同，同样产出需要的投入也可能不同。',
    trap:'“电力”和“能源”不是两个并列且互不相干的东西；电是一种能源载体。', question:'面包生产里，哪两个不同环节可能都用到电？', sources:['electricity'] },
  { ...common, id:'water', title:'水', en:'WATER', category:'nature', index:'02', x:110, y:310, icon:'water',
    summary:'它既是原料，也是食物系统的前提。',
    why:'面包配方里的水只是你看得见的部分；农作物的生长也依赖用水条件。',
    fact:'灌溉管理关注农业供水的效率、可靠性与分配。',
    mechanism:'把水看成“在合适的时间、到达合适位置的资源”，而不只是一个总量。路线图只表示用水依赖，不给出单块面包的耗水量。',
    inputs:['降水或水源','供水条件'], process:'获得与分配', outputs:['作物用水','加工用水'],
    recommendedBefore:[], failure:'水存在不等于可用；位置、时间和基础设施都可能形成约束。',
    trap:'只看配料表中的水，不能推算整个供应链的用水。', question:'“这里有水”和“农田在需要时能用到水”有什么区别？', sources:['water'] },
  { ...common, id:'agriculture', title:'农业', en:'AGRICULTURE', category:'making', index:'03', x:320, y:235, icon:'wheat',
    summary:'把自然条件与人的劳动，变成可用的原料。',
    why:'人需要持续获得食物，而不仅是偶然遇见它。种植是这条路线的生产起点。',
    fact:'FAO 的食物价值链框架把生产列为核心功能之一。',
    mechanism:'在面包的简化路线中，把土地、水、种子与劳动组织起来，获得谷物。现实还有品种、气候、设备和管理差异。',
    inputs:['土地与水','种子','劳动与设备'], process:'种植与收获', outputs:['谷物','后续加工原料'],
    recommendedBefore:['water'], failure:'产出会受种植条件影响；收获成功也不保证产品能到达消费者。',
    trap:'“有粮食”还不等于“有可随时购买的面包”。', question:'丰收之后，至少还缺哪两个环节才会出现货架上的面包？', sources:['fao-chain','water'] },
  { ...common, id:'processing', title:'加工', en:'PROCESSING', category:'making', index:'04', x:475, y:125, icon:'factory',
    summary:'原料没有直接变成午餐；有人完成了中间的变化。',
    why:'不同原料需要转换成适合后续使用的形态。加工把谷物与最终食品连接起来。',
    fact:'加工是食物价值链的核心功能，也属于 USDA 食品支出核算中的农场后环节。',
    mechanism:'这张图把磨粉与烘焙压缩成“加工”：原料经过设备、工序与协作，成为面包。它是教学压缩，不是工业工艺清单。',
    inputs:['谷物或面粉','能源','劳动'], process:'形态与用途转换', outputs:['可供分销的食品'],
    recommendedBefore:['agriculture','energy'], failure:'原料、设备和工序的任一瓶颈，都可能限制整条线的产出。',
    trap:'“加工”不是一种固定工艺，也不等于一个简单的好坏标签。', question:'即使原料充足，什么仍可能让工厂无法增加产量？', sources:['fao-chain','food-dollar'] },
  { ...common, id:'packaging', title:'包装', en:'PACKAGING', category:'making', index:'05', x:655, y:170, icon:'box',
    summary:'一个边界，让食品更容易被保护与传递。',
    why:'商品离开生产地点后，需要在搬运、储存和交接中保持可用状态。',
    fact:'食品包装有助于防止污染、维持卫生并保护食品完整性。',
    mechanism:'理解包装时，分别观察“保护了什么”与“传达了什么信息”。本示例不是说所有面包都要独立包装，也不是包装安全认证。',
    inputs:['食品','适用包装材料'], process:'容纳、保护与标识', outputs:['便于交接的商品','可阅读的信息'],
    recommendedBefore:['processing'], failure:'包装设计与实际使用条件不匹配时，原本的保护目标可能失效。',
    trap:'包装上的品牌地址不能直接证明原料来自那里。', question:'拿一个已有包装，区分你确实看到的信息与自己推断的信息。', sources:['packaging'] },
  { ...common, id:'transport', title:'运输', en:'TRANSPORT', category:'infrastructure', index:'06', x:810, y:310, icon:'truck',
    summary:'让“别处有”，变成“这里有”。',
    why:'生产地点与消费地点往往不同。运输解决空间上的分离。',
    fact:'运输属于食物供应链与食品营销成本的组成环节。',
    mechanism:'车辆、道路、燃料、人员和交接协作，把商品移动到下一站。运输费用只是零售支出的一部分，不等于完整价格。',
    inputs:['商品','运力与能源','路线信息'], process:'跨地点移动', outputs:['到达下一站的商品'],
    recommendedBefore:['packaging','energy'], failure:'路线或运力受阻时，商品可能无法按时到达；具体影响取决于库存与替代路线。',
    trap:'运输成本上涨 50%，不意味着面包价格也一定上涨 50%。', question:'如果运输只占成本的一小部分，它的变化会怎样传递？', sources:['food-dollar','fao-chain'] },
  { ...common, id:'storage', title:'储存', en:'STORAGE', category:'infrastructure', index:'07', x:650, y:435, icon:'store',
    summary:'把“现在有”，延伸到“需要时还有”。',
    why:'生产、配送与消费并不总在同一时刻发生。储存连接不同时间。',
    fact:'FAO 把储存列为收获后食物损失可能发生的环节之一。',
    mechanism:'库存为供需之间提供时间缓冲，但保存条件、空间与损失也需要考虑。不同食品的保存方式并不相同。',
    inputs:['商品','空间与管理'], process:'跨时间保存', outputs:['后续可用库存'],
    recommendedBefore:['transport'], failure:'缓冲并非无限；积压、短缺和损失都可能发生。',
    trap:'“储存”不等于“全部冷藏”。本页不提供食品安全判断。', question:'储存和运输分别解决了哪一种“不在一起”？', sources:['food-loss','fao-chain'] },
  { ...common, id:'retail', title:'零售', en:'RETAIL', category:'exchange', index:'08', x:465, y:475, icon:'shop',
    summary:'你看见的一排货架，是许多系统的交汇处。',
    why:'商品需要以消费者能够接近、选择和取得的方式呈现。',
    fact:'批发与零售属于 FAO 食物价值链框架中的分销功能。',
    mechanism:'这张图用一个零售节点代表门店的采购、陈列和交易组织。它连接上游货物与消费者需求，但不解释所有商业模式。',
    inputs:['商品与库存','场所','劳动'], process:'组织商品与交易', outputs:['消费者可获得的商品','需求反馈'],
    recommendedBefore:['storage','work'], failure:'有商品却不在顾客需要的时间或位置，仍可能出现错配。',
    trap:'零售价减去农场收入，不等于零售商利润；中间还包含许多环节。', question:'你为一块面包支付的金额，可能支持哪些不同活动？', sources:['fao-chain','food-dollar'] },
  { ...common, id:'work', title:'劳动与协作', en:'WORK / COORDINATION', category:'making', index:'09', x:425, y:310, icon:'people',
    summary:'不是一个人做完一切，而是许多人把事情接上。',
    why:'食物系统里的任务分散在不同参与者之间，需要彼此交接。',
    fact:'FAO 的框架包括价值链参与者之间的横向联系与上下游联系。',
    mechanism:'先问“谁做这一步”，再问“谁提供输入、接收输出”。把协作画出来，往往比列出职业名称更能看见系统。',
    inputs:['时间与技能','规则与沟通'], process:'分工与交接', outputs:['完成的任务','下一环节可用的结果'],
    recommendedBefore:[], failure:'各自完成任务也可能在接口处失败，例如信息、时点或规格不一致。',
    trap:'看不见某个人的劳动，不代表那一步自动发生。', question:'从农田到货架，写下三个不同参与者及他们的交接。', sources:['fao-chain'] },
  { ...common, id:'prices', title:'价格', en:'PRICES', category:'exchange', index:'10', x:285, y:505, icon:'price',
    summary:'一个数字，压缩了许多活动，却没有解释全部原因。',
    why:'价格让人能比较和交换；但理解变价，需要拆开其中的环节与假设。',
    fact:'USDA 的食品支出核算区分农场份额与加工、运输、销售等农场后活动。',
    mechanism:'先把问题改写成“哪个部分变了，怎样传递”。下面的价格实验是自编线性模型，不是定价理论全貌，也不是实际市场预测。',
    inputs:['成本与供需条件','交易环境'], process:'在具体市场中形成', outputs:['成交条件','可能的行为反馈'],
    recommendedBefore:['retail','transport'], failure:'只看到最终数字，可能把一次变化错误地归因于单一环节。',
    trap:'成本、销售收入、增加值与利润是不同概念；图上的模型不能把它们混用。', question:'还需要哪一种证据，才能区分“运输变贵”和其他解释？', sources:['food-dollar'] },
  { ...common, id:'information', title:'信息与证据', en:'INFORMATION / EVIDENCE', category:'exchange', index:'11', x:120, y:455, icon:'info',
    summary:'知道一条线存在，和证明它发生了，是两回事。',
    why:'一张说得通的关系图可以帮助提出问题，却不能替代对现实的检查。',
    fact:'伯克利的 Understanding Science 将科学描述为动态探索，而非一条僵硬的线性步骤。',
    mechanism:'把笔记分成三栏：观察到什么、推断了什么、仍缺什么证据。出现反例时改模型，不要只把故事讲得更圆。',
    inputs:['可追溯记录','明确问题'], process:'比较、核查与更新', outputs:['受到支持的判断','仍然未知的部分'],
    recommendedBefore:[], failure:'来源与问题不匹配时，真实资料也可能支持不了你的具体结论。',
    trap:'“可能经过这些环节”不等于“这包食品确实经过了这些公司或地点”。', question:'包装上的地址是一条观察；关于原料产地的结论还缺什么？', sources:['science'] },
  { ...common, id:'food', title:'食物供给', en:'FOOD SUPPLY', category:'exchange', index:'12', x:640, y:315, icon:'bread',
    summary:'一块面包，是一整套世界系统送到你手里的结果。',
    why:'我们需要的不只是生产出食物，还需要在合适的地方和时间获得它。',
    fact:'FAO 用生产、聚合、加工、分销等功能描述食物价值链。',
    mechanism:'从餐桌向后追踪：零售连接库存，库存连接运输，运输连接加工与农业；能源、水、劳动又支持多个环节。你正在读的是关系，不是孤立词条。',
    inputs:['食品与原料','基础设施','协作与交换'], process:'多环节连接', outputs:['在此时此地可获得的食物'],
    recommendedBefore:['agriculture','transport','retail'], failure:'某一环节中断，不一定意味着立刻断供；库存、替代路线和持续时间会改变结果。',
    trap:'这张图是教学模型，不是每种食物都必须按同一顺序通过的配方。', question:'把任意一条连接拿掉：什么会受影响？什么可能暂时不变？', sources:['fao-chain'] },
];

export const edges: Edge[] = [
  {from:'water',to:'agriculture',type:'support',label:'提供作物用水'},
  {from:'energy',to:'agriculture',type:'support',label:'支持设备运转'},
  {from:'energy',to:'processing',type:'support',label:'提供动力与热'},
  {from:'energy',to:'transport',type:'support',label:'支持移动'},
  {from:'agriculture',to:'processing',type:'flow',label:'提供谷物原料'},
  {from:'processing',to:'packaging',type:'flow',label:'交接加工产品'},
  {from:'packaging',to:'transport',type:'flow',label:'交付待运输商品'},
  {from:'transport',to:'storage',type:'flow',label:'送入库存'},
  {from:'storage',to:'retail',type:'flow',label:'补充可售商品'},
  {from:'retail',to:'food',type:'flow',label:'连接消费者获取'},
  {from:'work',to:'processing',type:'support',label:'参与生产工序'},
  {from:'work',to:'retail',type:'support',label:'组织销售与交接'},
  {from:'prices',to:'agriculture',type:'feedback',label:'可能影响生产选择'},
  {from:'retail',to:'prices',type:'support',label:'与交易条件相连'},
  {from:'information',to:'prices',type:'support',label:'支持核查变价解释'},
];
export const recipes: Recipe[] = [
  { id:'bread',relationMode:'flow',intentTerms:['怎么来的','从哪','来到餐桌','来源','供应链','supply chain'],title:'一块面包如何来到餐桌？',en:'FOLLOW A LOAF OF BREAD',description:'从一个熟悉的物品，发现背后协作的世界。',aliases:['面包','餐桌','食物','食品','bread','food','供应链','怎么来的','来源'],nodes:['agriculture','processing','packaging','transport','storage','retail','food'],outcome:'能够解释：为什么生产出食物，还不等于你能获得食物。' },
  { id:'cost',relationMode:'context',intentTerms:['变贵','涨价','成本','价格','price','expensive','通胀','运费'],title:'为什么食物会变贵？',en:'TRACE A CHANGE IN PRICE',description:'拆开成本变化、传递假设与仍然缺少的证据。',aliases:['变贵','涨价','成本','价格','price','expensive','groceries','通胀','运费'],nodes:['energy','processing','transport','retail','prices','information'],outcome:'能够区分：一种可能的变价机制，与已经被证据确认的原因。' },
];
export const questOrder = ['trace','predict','observe'];
export const questTitles = ['比较运输与储存','试算价格变化','看看食品包装'];
