"""UI checks on the exact built offline artifact, injected without navigation.

Chromium policy blocks all URL navigation in this environment. set_content exercises
rendered production HTML/JS; it does NOT verify hosting, native reload, or localStorage.
No browser policy or security setting is changed.
"""
from playwright.sync_api import sync_playwright, expect
from pathlib import Path
import json, os
OUT=Path(__file__).parent
HTML=(OUT.parent/'dist'/'EARTH-player-manual.html').read_text()
results=[]
def load(browser, mobile=False, reduced=False):
    page=browser.new_page(viewport={'width':390 if mobile else 1440,'height':844 if mobile else 900},device_scale_factor=1,is_mobile=mobile,has_touch=mobile,reduced_motion='reduce' if reduced else 'no-preference')
    page.set_default_timeout(3500)
    page.on('pageerror',lambda e: errors.append(str(e)))
    page.set_content(HTML,wait_until='load')
    return page
def route(page,path):
    page.evaluate('(path)=>{location.hash=path;window.dispatchEvent(new HashChangeEvent("hashchange"))}',path)
def no_overflow(page):
    assert page.evaluate('document.documentElement.scrollWidth <= innerWidth'), 'horizontal overflow'
with sync_playwright() as p:
    browser=p.chromium.launch(executable_path=os.environ.get('CHROMIUM_PATH') or ('/usr/bin/chromium' if Path('/usr/bin/chromium').exists() else None),args=['--no-sandbox'])
    errors=[]
    page=load(browser)
    expect(page.get_by_role('heading',name='EARTH.',exact=True)).to_be_visible()
    results.append('home rendered from built offline artifact')
    page.screenshot(path=str(OUT/'desktop-home.png'),full_page=True)
    page.get_by_role('link',name='展开世界地图').click()
    expect(page.get_by_role('heading',name='看见隐藏的连接。')).to_be_visible()
    page.get_by_role('button',name='选择 运输',exact=True).click()
    expect(page.locator('.node-panel h2')).to_have_text('运输')
    page.get_by_role('button',name='放大地图').click()
    expect(page.locator('#zoom-value')).to_have_text('115%')
    page.get_by_role('button',name='复位地图').click()
    expect(page.locator('#zoom-value')).to_have_text('100%')
    before=page.locator('#graph-transform').get_attribute('transform')
    page.locator('.desktop-map').focus();page.keyboard.press('ArrowRight')
    assert before!=page.locator('#graph-transform').get_attribute('transform')
    page.get_by_role('button',name='复位地图').click()
    box=page.locator('.desktop-map').bounding_box()
    before=page.locator('#graph-transform').get_attribute('transform')
    page.mouse.move(box['x']+45,box['y']+45);page.mouse.down()
    page.mouse.move(box['x']+95,box['y']+75,steps=5);page.mouse.up()
    assert before!=page.locator('#graph-transform').get_attribute('transform')
    assert not page.locator('.desktop-map').evaluate('(el)=>el.classList.contains("dragging")')
    page.get_by_role('button',name='复位地图').click()
    node=page.get_by_role('button',name='选择 储存',exact=True)
    node.focus();page.keyboard.press('Enter')
    expect(page.locator('.node-panel h2')).to_have_text('储存')
    expect(page.get_by_role('button',name='选择 储存',exact=True)).to_be_focused()
    results.append('atlas selection, mouse drag, zoom/reset, keyboard pan and node focus')
    page.get_by_role('button',name='选择 运输',exact=True).click()
    page.screenshot(path=str(OUT/'desktop-atlas.png'),full_page=True)
    page.get_by_role('link',name='打开系统说明').click()
    expect(page.get_by_role('heading',name='运输',exact=True)).to_be_visible()
    page.screenshot(path=str(OUT/'desktop-guide.png'),full_page=True)
    results.append('atlas to guide navigation')
    page.keyboard.press('Control+k')
    expect(page.get_by_role('dialog')).to_be_visible()
    page.get_by_role('combobox').fill('食物为什么变贵')
    expect(page.get_by_role('option',name='为什么食物会变贵？',exact=False)).to_be_visible()
    page.screenshot(path=str(OUT/'desktop-search.png'),full_page=True)
    page.keyboard.press('Enter')
    expect(page.locator('.recipe-detail h2')).to_contain_text('为什么食物会变贵')
    page.keyboard.press('Control+k');page.get_by_role('combobox').fill('如何申请火星土地许可证')
    expect(page.locator('.search-empty')).to_contain_text('这片知识还没有收录')
    page.keyboard.press('Escape')
    expect(page.get_by_role('dialog')).not_to_be_visible()
    results.append('task-aware search, recipe mapping, honest unknown and Escape')
    route(page,'quests/observe')
    expect(page.locator('.locked-quest')).to_be_visible()
    page.get_by_role('link',name='继续当前任务').click()
    page.get_by_label('只是为了把价格抬高').check()
    page.get_by_role('button',name='检验判断').click()
    expect(page.locator('#quest-feedback')).to_contain_text('再想一步')
    page.get_by_label('运输连接地点，储存连接时间').check()
    page.get_by_role('button',name='检验判断').click()
    expect(page.locator('#quest-feedback')).to_contain_text('判断成立')
    assert page.locator('a.quest-step[href="#quests/predict"] > svg').count()==0
    page.get_by_role('link',name='进入下一步').click()
    page.screenshot(path=str(OUT/'desktop-experiment.png'),full_page=True)
    expect(page.locator('#model-value')).to_have_text('?')
    page.get_by_label('150：把一个环节的变化直接应用于整体').check()
    page.get_by_role('button',name='检验预测').click()
    expect(page.locator('#quest-feedback')).to_contain_text('再检查一下')
    expect(page.locator('#model-value')).to_have_text('105.0')
    page.locator('#pass').fill('50')
    expect(page.locator('#model-value')).to_have_text('?')
    page.get_by_label('102.5：只改变受影响的那一部分').check()
    page.get_by_role('button',name='检验预测').click()
    expect(page.locator('#quest-feedback')).to_contain_text('预测成立')
    page.get_by_role('link',name='进入下一步').click()
    page.get_by_label('我确实观察到').fill('我看到家里这包面包的包装上印有生产商名称与地址。')
    route(page,'atlas'); route(page,'quests/observe')
    expect(page.get_by_label('我确实观察到')).to_have_value('我看到家里这包面包的包装上印有生产商名称与地址。')
    page.get_by_label('我的推断是').fill('它可能经过包装、运输与零售环节。')
    page.get_by_label('我仍然不知道').fill('不知道小麦的种植地点，需要可追溯的原料记录。')
    page.get_by_label('我理解：包装地址不等于原料产地；这份观察仅由我本人报告。').check()
    page.get_by_role('button',name='保存观察，完成路线').click()
    expect(page.locator('.quest-complete h1')).to_contain_text('一块面包之外的世界。')
    route(page,'atlas'); route(page,'quests')
    expect(page.locator('.quest-complete h1')).to_contain_text('一块面包之外的世界。')
    page.screenshot(path=str(OUT/'desktop-complete.png'),full_page=True)
    results.append('ordered complete loop, wrong-answer recovery, hidden prediction, live variables, draft retention and same-session progress')
    page.once('dialog',lambda d:d.dismiss())
    page.get_by_role('button',name='重新开始这条路线').click()
    expect(page.locator('.quest-complete')).to_be_visible()
    page.once('dialog',lambda d:d.accept())
    page.get_by_role('button',name='重新开始这条路线').click()
    expect(page.locator('.quest-count strong')).to_have_text('00')
    results.append('progress deletion requires confirmation; cancel preserves data')
    route(page,'nonsense')
    expect(page.locator('main')).to_contain_text('这片区域还没有收录')
    results.append('unknown route fallback')
    mobile=load(browser,mobile=True)
    no_overflow(mobile)
    mobile.screenshot(path=str(OUT/'mobile-home.png'),full_page=True)
    mobile.get_by_role('link',name='展开世界地图').click()
    expect(mobile.locator('.mobile-node-explorer')).to_be_visible()
    mobile.locator('#mobile-node-select').select_option('transport')
    expect(mobile.locator('.mobile-focus strong')).to_have_text('运输')
    no_overflow(mobile)
    mobile.screenshot(path=str(OUT/'mobile-atlas.png'),full_page=True)
    mobile.get_by_role('link',name='打开系统说明').click()
    no_overflow(mobile)
    mobile.screenshot(path=str(OUT/'mobile-guide.png'),full_page=True)
    route(mobile,'quests/trace')
    no_overflow(mobile)
    mobile.screenshot(path=str(OUT/'mobile-quest.png'),full_page=True)
    mobile.get_by_role('button',name='搜索系统或现实问题').click()
    expect(mobile.get_by_role('dialog')).to_be_visible()
    no_overflow(mobile)
    mobile.screenshot(path=str(OUT/'mobile-search.png'),full_page=True)
    results.append('mobile focused explorer, guide, quest, search and no page overflow at 390x844')
    reduced=load(browser,reduced=True)
    assert reduced.evaluate('matchMedia("(prefers-reduced-motion: reduce)").matches')
    reduced.get_by_role('link',name='展开世界地图').click()
    expect(reduced.locator('.node-panel')).to_be_visible()
    results.append('reduced-motion rendering and navigation')
    assert not errors,errors
    report={'status':'passed','consoleErrors':errors,'method':'Production offline HTML injected with Playwright set_content; no URL navigation or policy changes','viewports':['1440x900','390x844'],'checks':results,'unverified':['Native localStorage across reload or browser restart','Hosted URL and real file:// navigation; environment policy blocks all navigation','Human learning outcomes and real-user usability']}
    (OUT/'browser-report.json').write_text(json.dumps(report,ensure_ascii=False,indent=2))
    print(json.dumps(report,ensure_ascii=False,indent=2))
    browser.close()
